---
# Common part
- name: Install ufw
  ansible.builtin.package:
    name: ufw
    state: present

- name: Start and enable ufw
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes

- name: Allow out and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
    direction: out

# Rules
- name: Configure ufw for HA
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ vip_port }}"
  when: inventory_hostname in groups['kube_masters']

# VRRP Settings
- name: Allow VRRP traffic
  community.general.ufw:
    rule: allow
    dest: "224.0.0.18"
    comment: "VRRP Broadcast"
